import Modal from '@/components/Modal'
import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Trello Appwrite',
  description: 'Generated by create next app',
}

const sahel = localFont({
  src: [{
    path: '../public/fonts/Sahel-Bold-FD.ttf',
    weight: '500',
    style:"bold"
  },
    {
      path: '../public/fonts/Sahel-FD.ttf',
      weight: '400',
      style:"normal"
    },
  ],
  variable: '--font-sahel'
})

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en" dir='ltr'>
      <body className={`${sahel.variable} font-sans bg-background`}>
        {children}
        <Modal />
      </body>
    </html>
  )
}
